### ISSUE TITLE
HumbleViewPager consistently crashes due to null View

### ISSUE THREAD

**Issue by nasahapps** [button/button-android#4]
In the `onMeasure()` method, in this snippet of code:

```
View title = this.findViewById(com.usebutton.sdk.R.id.promo_pager_title);
if (title.getVisibility() != 8) {
    title.measure(widthSpec, MeasureSpec.makeMeasureSpec(maxHeight - measuredHeight, -2147483648));
    measuredHeight += title.getMeasuredHeight();
}
```

The `title` view is sometimes null, thus resulting in a NullPointerException when `getVisibility()` is called. A null-check needs to be performed on this variable and any other potential nullable views.

This bug exists in at least version 4.3.2 of the library, including the most recent version (5.0.0)

**Comment by sveinungkb** [comment]
Resolved through other channels with reporter, but this is an issue with the Button SDK and most other users of decor views (like PagerTitleStrip) inside of a ViewPager and the way the decor views were marked and kept from being removed on paging in android support v4's version 24.0.0.

We released our fix in version [5.0.1 of our SDK](https://github.com/button/button-android#501-docs). You can also use any version of the support-v4 library before or after 24.0.0, latest is always recommended.

Android Issue [#233559](https://code.google.com/p/android/issues/detail?id=213359)
